### ISSUE TITLE
"Parser library path is 'None'."

### ISSUE THREAD

**Issue by qwertie** [autosoft-dev/tree-hugger#1]
After doing `pip install tree-hugger`, installing the VC++ build tools, rebooting and running `create_libs python`, everything seemed to be ready on my Windows 10 PC (which has WSL installed - not sure if that's important).

However, the following example produces an exception:

~~~py
from tree_hugger.core import PythonParser
def my_func():
  pp = PythonParser()
  pp.parse_file("try_tree_hugger.py")
  print(pp.get_all_function_names())
my_func()
~~~

~~~
  File ".\try_tree_hugger.py", line 8, in <module>
    my_func()
  File ".\try_tree_hugger.py", line 4, in my_func
    pp = PythonParser()
  File "C:\Users\Family\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tree_hugger\core\python_parser.py", line 31, in __init__
    super(PythonParser, self).__init__('python', 'python_quaries', library_loc, query_file_path)
  File "C:\Users\Family\AppData\Local\Programs\Python\Python38-32\lib\site-packages\tree_hugger\core\code_parser.py", line 33, in __init__
    raise ParserLibraryNotFoundError("Parser library path is 'None'. Please either set up the environment or call the constructor with the path")
tree_hugger.exceptions.ParserLibraryNotFoundError: Parser library path is 'None'. Please either set up the environment or call the constructor with the path
~~~

**Comment by rcshubhadeep** [comment]
Hello @qwertie Thanks a lot for reporting an issue. I have to be honest, I have not tried it on Windows. So I will be generally curious to know how that goes. However, regarding the particular error you faced, Here is the thing

- Please note that, you can set up two environment variables QUERY_FILE_PATH and TS_LIB_PATH for the query file path and tree-sitter lib path and then the libary will use them automatically. Otherwise, as an alternative, you can pass it when creating any *Parser object. 

In your case, can you please try to set up these two env vars (You will need to download the example query file, or write your own. You can download the example one [here](https://raw.githubusercontent.com/autosoft-dev/tree-hugger/master/queries/example_queries.yml))

Please try this and let me know how it went. I am very keen to know.

Once again, thanks for trying out tree-hugger :)

**Comment by rcshubhadeep** [comment]
Hi @qwertie, curious to know if what I said helped or not? Did you finally make it work?

**Comment by rcshubhadeep** [comment]
Hey, I am marking it as closed, as I did not hear anything. Feel free to open it if there are still some issues somewhere
